name: CoinFlip
main: BajanVlogs\\CoinFlip
version: 1.0
api: 5.0.0
description: Simple CoinFlip Plugin For PMMP!
author: BajanVlogs

commands:
  coinflip:
    description: "Flips A Coin! returns heads or tails"
    permission: coinflip.flip
    usage: "/coinflip"

permissions:
  coinflip.flip:
    default: true
